include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - third_party/**
    - build/**
    - android/**
    - ios/**
    - windows/**
    - linux/**

linter:
  rules:
    - public_member_api_docs